### ISSUE TITLE
Not working with all valid AltSources

### ISSUE THREAD

**Issue by noah978** [therealFoxster/altsource-viewer#1]
Hey!

I work a lot with AltStore Sources and I love what you did here! I've been waiting for an actually solid web utility to preview AltSources.

I haven't had the chance to look through your code yet, but I wanted to mention that none of my sources on https://quarksources.github.io seem to quite work properly on your preview despite them working fine in AltStore.

Check out [Quantum Source for example.](https://therealfoxster.github.io/altsource-viewer/index.html?source=https://quarksources.github.io/dist/quantumsource.min.json)

If I had to guess, you're code might be running into extra tags that [AltSource Parser](https://github.com/noah978/AltSourceParser) uses when keeping apps up-to-date with github repos (absoluteVersion, etc), and then it freaks out and stops processing the apps without throwing a proper error, but it seems to like it might be slightly more complicated than that. We love JavaScript :P

Anyways, kudos to you on making this site! The AltStore Team is most likely going to give this project a shoutout too and it'd be huge if it works with the two big QS sources.

**Comment by therealFoxster** [comment]
Hey thanks for reporting! The problem was that I made it so that the page won't show up until all images are loaded, so if one of them fails to load for whatever reason you'll never get pass the loading screen. I have addressed this in cfb4d98 and it should now be able to handle missing images, though this is not ideal and you should try to replace/remove broken image links in your sources. Let me know if you find any other issues!
